version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "DerLev"
    labels:
      - "dependabot/gh-actions"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    assignees:
      - "DerLev"
    labels:
      - "dependabot/yarn"
    open-pull-requests-limit: 10
