name: eslint-annotations
description: Annotates Code directly in GitHub with output of ESLint and TypeScript

inputs:
  eslint-report:
    description: Location of the ESLint report file
    default: ''
  eslint-annotation-prefix:
    description: Prefix for ESLint annotations
    default: 'ESLint Rule:'
  typescript-log:
    description: Location of the Typescript log file
    default: ''
  typescript-annotation-prefix:
    description: Prefix for Typescript annotations
    default: 'Typescript Error:'
  error-on-warn:
    description: Whether the action should fail when ESLint only throws a warn
    default: 'false'
  github-token:
    description: GitHub token for accessing the API
  create-status-check:
    description: Whether to create a seperate status check or not
    default: 'true'
  status-check-name:
    description: Name of the status check created
    default: 'eslint-annotations'
  failed-attempts:
    description: IDs of failed attempts to stop status checks from running
  fail-in-pr:
    description: Whether the action should fail in a PR
    default: 'true'
  only-changed-in-pr:
    description: Whether the action should only annotate changed files in a pull request
    default: 'true'
  add-notice-with-url:
    description: Enable or disable the notice added to the workflow logs containing the link to the status check
    default: 'true'

runs:
  using: 'node20'
  main: 'dist/action.js'

branding:
  color: 'green'
  icon: 'check'
