name: eslint-annotations
description: Annotates Code directly in GitHub with output of ESLint

inputs:
  eslint-report:
    description: Location of the ESLint report file
    default: ''
  eslint-annotation-prefix:
    description: Prefix for ESLint annotations
    default: 'ESLint Rule:'
  typescript-log:
    description: Location of the Typescript log file
    default: ''
  typescript-annotation-prefix:
    description: Prefix for Typescript annotations
    default: 'Typescript Error:'
  error-on-warn:
    description: Whether the action should fail when ESLint only throws a warn
    default: 'false'
  github-token:
    description: GitHub token for accessing the API
  create-status-check:
    description: Whether to create a seperate status check or not
    default: 'true'

runs:
  using: 'node16'
  main: 'dist/action.js'

branding:
  color: 'green'
  icon: 'check'
