name: Build Action
on:
  workflow_dispatch:

jobs:
  build-and-commit:
    name: Build Action & Commit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Nodejs environment
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "yarn"
      - name: Install Dependencies
        run: yarn
      - name: Lint Action
        run: yarn lint
      - name: Type Check
        run: yarn tsc
      - name: Remove old dist
        run: rm -rf dist
      - name: Build Action
        run: yarn build
      - name: Commit Changes
        uses: EndBug/add-and-commit@v9
        with:
          add: 'dist'
          default_author: github_actions
          message: 'Workflow: Build action'
          pathspec_error_handling: exitAtEnd
          new_branch: gh-actions/build-${{ github.run_number }}-${{ github.run_attempt }}
