name: Build Action
on:
  workflow_dispatch:
    inputs:  
      version:
        description: Version number of PR
        default: v0.0.0

jobs:
  build-and-commit:
    name: Build Action & Commit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Nodejs environment
        uses: actions/setup-node@v4
        with:
          node-version: 16
          cache: "yarn"
      - name: Install Dependencies
        run: yarn --frozen-lockfile
      - name: Lint Action
        run: yarn lint
      - name: Type Check
        run: yarn tsc
      - name: Remove old dist
        run: rm -rf dist
      - name: Build Action
        run: yarn build
      - name: Commit Changes
        uses: EndBug/add-and-commit@v9
        with:
          add: 'dist'
          default_author: github_actions
          message: 'Workflow: Build action'
          pathspec_error_handling: exitAtEnd
          new_branch: gh-actions/build-${{ github.run_number }}-${{ github.run_attempt }}
      - name: Open Pull Request
        uses: actions/github-script@v6
        with:
          script: |
            const { repo, owner } = context.repo;
            const result = await github.rest.pulls.create({
              title: '${{ inputs.version }}',
              owner,
              repo,
              head: 'gh-actions/build-${{ github.run_number }}-${{ github.run_attempt }}',
              base: 'main',
              body: [
                '**This PR is auto-generated by GitHub Actions**  ',
                'New version of action: ${{ inputs.version }}'
              ].join('\n')
            });
            github.rest.issues.addLabels({
              owner,
              repo,
              issue_number: result.data.number,
              labels: ['type/new-build']
            });
