name: Test Action
on:
  workflow_dispatch:

jobs:
  build-and-test:
    name: Build & Run Action
    runs-on: ubuntu-latest
    if: ${{ !startsWith(github.event.head_commit.message, 'wip:') }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Nodejs environment
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "yarn"
      - name: Install Dependencies
        run: yarn
      - name: Lint Action
        run: yarn lint --output-file eslint_report.json --format json
      - name: Build Action
        run: npm run build -- --outDir dist > typescript.log
      - name: Test Action
        uses: ./
        with:
          eslint-report: eslint_report.json
          typescript-log: typescript.log
