name: Test Action
on:
  workflow_dispatch:

jobs:
  build-and-test:
    name: Build & Run Action
    runs-on: ubuntu-latest
    if: ${{ !startsWith(github.event.head_commit.message, 'wip:') }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Nodejs environment
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "yarn"
      - name: Install Dependencies
        run: yarn
      - name: Lint Action
        run: yarn lint --output-file eslint_report.json --format json
        continue-on-error: true
      - name: Build Action
        run: npm run build --outDir dist > typescript.log
        continue-on-error: true
      - name: Upload logs as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: test-output
          path: |
            typescript.log
            eslint_report.json
      # - name: Test Action
      #   uses: ./
