name: Test Action
on:
  workflow_dispatch:
    inputs:
      create-status-check:
        description: Create Status Check
        type: boolean
        default: true
      failed_attempts:
        description: Failed Attempt IDs
        type: string

jobs:
  build-and-test:
    name: Build & Run Action
    runs-on: ubuntu-latest
    if: ${{ !startsWith(github.event.head_commit.message, 'wip:') }}
    permissions:
      checks: write
      pull-requests: read
      contents: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Nodejs environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "yarn"
      - name: Install Dependencies
        run: yarn --frozen-lockfile
      - name: Lint Action
        run: yarn lint --output-file eslint_report.json --format json
      - name: Type Check Action
        run: yarn tsc > typescript.log
      - name: Build Action
        run: yarn build
      - name: Test Action with current Output
        uses: ./
        with:
          eslint-report: eslint_report.json
          typescript-log: typescript.log
      - name: Test Action with test Output
        uses: ./
        with:
          eslint-report: src/__tests__/test_eslint_report.json
          typescript-log: src/__tests__/test_typescript.log
          error-on-warn: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          create-status-check: ${{ inputs.create-status-check }}
          status-check-name: action-test
          failed-attempts: ${{ inputs.failed_attempts }}
        continue-on-error: true
